### ISSUE TITLE
Upgrade to symfony 2.6 compatible form extensions

### ISSUE THREAD

**Issue by kralos** [braincrafted/bootstrap-bundle#374]
As of symfony 2.6

```php
public function configureOptions(OptionsResolver $resolver)
{
    $resolver->setDefined(array(/** 'option1', 'option2' */));
}
```

should be used instead of:
```php
public function setDefaultOptions(OptionsResolverInterface $resolver)
{
    $resolver->setOptional(array(/** 'option1', 'option2' */));
}
```

As of 2.7 the former method is also deprecated

**Comment by althaus** [comment]
:+1:

**Comment by kralos** [comment]
Fixed https://github.com/braincrafted/bootstrap-bundle/pull/375

**Comment by althaus** [comment]
You missed to update the form types accordingly. I'll prepare a separate PR to fix this issue.

**Comment by althaus** [comment]
Sorry for the two commits here. Missed to tell the repo to not f*** up the lineendings at first. :hammer:
