### ISSUE TITLE
Support for Symfony 3.0

### ISSUE THREAD

**Issue by gpilla** [braincrafted/bootstrap-bundle#408]
Dependencies as symfony/finder should be for 3.0 ... ~2.6 is not enough, should be something like >=2.6 ... I did nt test if there is any mayor change that brokes the Bundle.

**Comment by dkisselev** [comment]
I think there are still a few deprecation issues which I'm not certain were patched (search the tracker for 'deprecation', the discussion is unclear if the issues have been patched on develop), but mostly we need to test that everything in the develop branch works before florian will push a new release out.

#396 is probably going to be the discussion thread about 1 3.0-compatible dot-release, so post anything broken that you can find there.

**Comment by dkisselev** [comment]
@gpilla, I just tested things and the bundle is pretty good on Symfony 2.8.

The only remaining deprecations for 3.0 are:

Accessing type "button" by its string name is deprecated since version 2.8 and will be removed in 3.0.
Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\ButtonType" instead

(there's one for each type of form output)

That's going to take a few more fixes. We're not switching to 3.0 yet so I probably won't have a chance to fix it for the time being.

**Comment by netsuo** [comment]
There's unfortunately more than that, example:

- Braincrafted\Bundle\BootstrapBundle\Form\Extension\StaticControlExtension: The FormTypeExtensionInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0

- Returning a type name from Braincrafted\Bundle\BootstrapBundle\Form\Extension\ButtonTypeExtension::getExtendedType() is deprecated since version 2.8 and will be removed in 3.0

And also a lot of deprecations for Twig 2.0 raised.

**Comment by dkisselev** [comment]
@netsuo are you looking at the develop branch? A lot of things have been fixed in the last ~2 weeks there (most of the twig 2.0 stuff).

**Comment by netsuo** [comment]
I'm using dev-master. I don't see what I've done wrong because I still have a twigi depreciations and what I've listed before

**Comment by lashus** [comment]
Is there any chances that dev-master will be 3.0 compatible this month?

**Comment by dkisselev** [comment]
@lashus only if someone contributes the fixes, florian sounds to be really busy so he probably won't have a chance to.

@netsuo my bad, I guess you're using the bundle in more complicated ways than we are.

**Comment by lashus** [comment]
@dkisslev I will fork the repo and provide fixes then. Which branch shall I use? I see the develop one, 3.0-exp one and master. Not sure which one would be best.

**Comment by dkisselev** [comment]
develop is where all the activity has been happening recently, so that would probably be the best spot.

One thing to look out for is the ::class magic method, the Symfony docs now recommend that as how you should refer to form types (which is what the form type string name deprecations are signaling), but that method does not exist on PHP 5.3/5.4 which Symfony 2.8 and this bundle should still support. I believe the solution is to insert the fully-qualified class name as a string instead.

**Comment by lashus** [comment]
@dkisselev The other proper solution would be to check for either php version / magic method support and use the proper action accordingly.

**Comment by netsuo** [comment]
My bad, I understood the problem: you have to use "dev-develop" version in composer to have the actual latest code.

The twig depreciations are now gone but there's still the others I mentioned.

**Comment by lashus** [comment]
I have a little offtop here but it appeared during the development.

File: InstallCommandTest.php (Tests/Command)
Line: 160

Why do we test creating an invalid directory? And how could this test possibly work? it is all reliant on filesystem permissions am I wrong?

**Comment by lashus** [comment]
Also @dkisselev Where did you found reference to ::class method? I don't see it in documentation.

**Comment by florianeckerstorfer** [comment]
As @dkisselev pointed out I'm super busy right now with work, finishing my masters thesis and the holidays coming up. I really hope I can manage a new dot release this weekend.

**Comment by lashus** [comment]
I've managed to get this working under 3.0 on my fork (although i'm working on how-to create pull-request, I didn't have much in common with GH). It would be great if someone could take a look at it.

@lashus/bootstrap-bundle

**Comment by Craimasjien** [comment]
I'd really like a dot release too. Any news?

**Comment by lashus** [comment]
@florianeckerstorfer what do you think? :)

**Comment by melroy89** [comment]
@florianeckerstorfer waiting?

**Comment by Bubelbub** [comment]
No activity here? :-(
